### ISSUE TITLE
logger.critical(...) does not set PRIORITY

### ISSUE THREAD

**Issue by breuleux** [mosquito/logging-journald#8]
The `LogRecord` produced by `logger.critical(...)` effectively sets `message_level = 0` and should set `PRIORITY=0` in the journal, but properties that are equal to 0 are not included in the journal entry because of this line:

https://github.com/mosquito/logging-journald/blob/master/logging_journald.py#L93

I assume you meant something like `if value is None:`.

**Comment by mosquito** [comment]
Yep.

**Comment by BonaFideIT** [comment]
Since the #9 was merged, this issue can be closed?
